### ISSUE TITLE
Creating other boards is forbidden?

### ISSUE THREAD

**Issue by MusicDisc5** [SebLague/Chess-Challenge#72] opened 2023-07-21 18:17 UTC
when I  create another other Board object in the code (Board a = new Board();), the mouse hover says "Create a new board. Note: this should not be used in the challange, use the board provided in the think method instead". So can I use other boards in my calculation code? Or did I miss something and its forbidden?

**Comment by MinekPo1** [comment] 2023-07-21 18:19
Duplicate of #48. Please check open and closed issues before creating a new issue.

**Comment by SebLague** [comment] 2023-07-21 19:56
Hi, I've added: public static Board CreateBoardFromFEN(string fen) to the board class in V1.1
Please note that this is quite slow, so I'd generally recommend using the MakeMove and UndoMove functions on the board provided in the think function instead.

**Closed by SebLague** 2023-07-21 19:56 UTC
