### ISSUE TITLE
Finding out what color the bot is.

### ISSUE THREAD

**Issue by Scrapmine** [SebLague/Chess-Challenge#66] opened 2023-07-21 17:32 UTC
Title.

**Comment by MinekPo1** [comment] 2023-07-21 17:34
Duplicate of #60. Try checking open and *closed* issues before posting a issue next time.

**Comment by Gavin-TC** [comment] 2023-07-21 17:47
you can use this: `var color = board.IsWhiteToMove ? true : false;`, but yeah duplicate.

**Comment by MinekPo1** [comment] 2023-07-21 17:51
@Gavin-TC I sincerely hope you have done that on purpose. I don't have much faith in humanity left so I am unsure.

**Comment by Gavin-TC** [comment] 2023-07-21 17:52
@MinekPo1 wow I just realized. I got 4 hours of sleep hahaha

**Closed** 2023-07-21 18:12 UTC
