### ISSUE TITLE
How can I get the list of all the moves made?

### ISSUE THREAD

**Issue by MathabsUnity** [SebLague/Chess-Challenge#100] opened 2023-07-21 21:17 UTC
How can I get the list of all the moves made (1. e4 e5 2. Nf3 Nc6...)?

**Comment by AugsEU** [comment] 2023-07-21 21:20
The documentation doesn't have that function. Looks like you would need to keep track of that in the chess bot. I don't see why moves in the past would matter anyway.

**Comment by dr-vortex** [comment] 2023-07-21 22:01
Duplicate of #92

**Comment by SebLague** [comment] 2023-07-22 03:37
Closing as duplicate

**Closed** 2023-07-22 03:43 UTC
