### ISSUE TITLE
No Pieces showing in game board

### ISSUE THREAD

**Issue by galord123** [SebLague/Chess-Challenge#254] opened 2023-07-23 19:30 UTC
The board is not showing any pieces, no matter what game mode I am trying.
As follows:
![image](https://github.com/SebLague/Chess-Challenge/assets/72351424/5d2fbdcc-acce-444d-bdff-ed43b86cde64)

my dotnet info is: 
```
.NET SDK (reflecting any global.json):
 Version:   6.0.315
 Commit:    2282fe998c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   C:\Program Files (x86)\dotnet\sdk\6.0.315\

global.json file:
  Not found

Host:
  Version:      6.0.20
  Architecture: x86
  Commit:       a08d9ce2ca

.NET SDKs installed:
  6.0.315 [C:\Program Files (x86)\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.20 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.20 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
```

my Raylib version is 4.5.0.2.

What can I do?

**Comment by crp222** [comment] 2023-07-23 20:15
I have the same problem, #247
What graphics card you have?

**Comment by SebLague** [comment] 2023-07-23 22:36
This issue seems to occur when the path to the project contains letters with diacritics. Would you mind posting the path to your project or confirming if it has any non-ascii characters? Currently looking into a solution

**Comment by SebLague** [comment] 2023-07-23 22:45
Closing as duplicate of #247

**Closed by SebLague** 2023-07-23 22:45 UTC
